"""Initial

Revision ID: c54d1d60eb0e
Revises: efc7d2f6d6ac
Create Date: 2025-10-30 01:30:41.676516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c54d1d60eb0e'
down_revision: Union[str, Sequence[str], None] = 'efc7d2f6d6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('services', sa.JSON(), nullable=True))
    op.drop_column('hotels', 'servises')
    op.add_column('rooms', sa.Column('services', sa.JSON(), nullable=True))
    op.drop_column('rooms', 'servises')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('servises', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'services')
    op.add_column('hotels', sa.Column('servises', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('hotels', 'services')
    # ### end Alembic commands ###
