"""Initial

Revision ID: da0d823a9e3b
Revises: c54d1d60eb0e
Create Date: 2025-10-30 01:32:03.027608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0d823a9e3b'
down_revision: Union[str, Sequence[str], None] = 'c54d1d60eb0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('rooms', 'quantiti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('quantiti', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'quantity')
    # ### end Alembic commands ###
